"""
Unit tests for AI Voice Detector API.
Run with: pytest tests/test_api.py -v
"""
import pytest
import base64
import json
import os
import sys
from fastapi.testclient import TestClient

# Add parent directory to path so we can import voice_detector
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# Set API_KEY for testing
os.environ["API_KEY"] = "test-api-key-12345"

from voice_detector.app import app

client = TestClient(app)

# Sample test audio file paths (generated by generate_test_audio.py)
TEST_AUDIO_DIR = "tests/audio_samples"


def load_test_audio(filename: str) -> bytes:
    """Load test audio file."""
    filepath = os.path.join(TEST_AUDIO_DIR, filename)
    if not os.path.exists(filepath):
        pytest.skip(f"Test audio file not found: {filepath}. Run generate_test_audio.py first.")
    
    with open(filepath, "rb") as f:
        return f.read()


def test_health_check():
    """Test the health check endpoint."""
    response = client.get("/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"


def test_detect_valid_audio_with_bearer_auth():
    """Test detection with Bearer token authentication."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "en"
        },
        headers={"Authorization": "Bearer test-api-key-12345"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert "result" in data
    assert "confidence" in data
    assert data["result"] in ["AI_GENERATED", "HUMAN"]
    assert isinstance(data["confidence"], float)
    assert 0.0 <= data["confidence"] <= 1.0


def test_detect_valid_audio_with_api_key_header():
    """Test detection with x-api-key header authentication."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "en"
        },
        headers={"x-api-key": "test-api-key-12345"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert "result" in data
    assert "confidence" in data


def test_detect_all_supported_languages():
    """Test detection for all supported languages."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    supported_langs = ["en", "ta", "hi", "ml", "te"]
    
    for lang in supported_langs:
        response = client.post(
            "/detect",
            json={
                "audio_base64": audio_base64,
                "language": lang
            },
            headers={"Authorization": "Bearer test-api-key-12345"}
        )
        
        assert response.status_code == 200, f"Failed for language: {lang}"
        data = response.json()
        assert "result" in data
        assert "confidence" in data


def test_detect_unsupported_language():
    """Test that unsupported language returns 400."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "fr"  # French not supported
        },
        headers={"Authorization": "Bearer test-api-key-12345"}
    )
    
    assert response.status_code == 400
    data = response.json()
    assert "detail" in data


def test_detect_missing_auth():
    """Test that missing authentication returns 401."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "en"
        }
        # No auth header
    )
    
    assert response.status_code == 401


def test_detect_invalid_auth_key():
    """Test that invalid API key returns 401."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "en"
        },
        headers={"Authorization": "Bearer wrong-api-key"}
    )
    
    assert response.status_code == 401


def test_detect_invalid_base64():
    """Test that invalid base64 returns 400."""
    response = client.post(
        "/detect",
        json={
            "audio_base64": "not-valid-base64!!!",
            "language": "en"
        },
        headers={"Authorization": "Bearer test-api-key-12345"}
    )
    
    assert response.status_code == 400
    data = response.json()
    assert "detail" in data
    assert "base64" in data["detail"].lower()


def test_detect_too_small_file():
    """Test that very small audio file returns 400."""
    # Create a tiny base64 "audio" that's too small
    tiny_data = b"x" * 50  # Only 50 bytes
    audio_base64 = base64.b64encode(tiny_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "en"
        },
        headers={"Authorization": "Bearer test-api-key-12345"}
    )
    
    assert response.status_code == 400


def test_confidence_precision():
    """Test that confidence is rounded to 3 decimals."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "en"
        },
        headers={"Authorization": "Bearer test-api-key-12345"}
    )
    
    assert response.status_code == 200
    data = response.json()
    confidence = data["confidence"]
    
    # Check that it's rounded to at most 3 decimals
    confidence_str = str(confidence)
    if "." in confidence_str:
        decimals = len(confidence_str.split(".")[1])
        assert decimals <= 3, f"Confidence has too many decimal places: {confidence}"


def test_response_only_contains_result_and_confidence():
    """Test that response contains only result and confidence fields."""
    audio_data = load_test_audio("test_sine_2s.mp3")
    audio_base64 = base64.b64encode(audio_data).decode()
    
    response = client.post(
        "/detect",
        json={
            "audio_base64": audio_base64,
            "language": "en"
        },
        headers={"Authorization": "Bearer test-api-key-12345"}
    )
    
    assert response.status_code == 200
    data = response.json()
    
    # Check that response contains exactly these keys
    expected_keys = {"result", "confidence"}
    actual_keys = set(data.keys())
    assert actual_keys == expected_keys, f"Response has unexpected keys: {actual_keys - expected_keys}"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
